### ISSUE TITLE
Creating CsvParser

### ISSUE THREAD

**Issue by spiralfuzet** [spiralfuzet/AirportSimulation#11]

**Comment by gbrdbs** [comment]
Ez fontos?

**Comment by gbrdbs** [comment]
task 15 és 16-hoz tartozó branchen minta (15-16_Defining-csv-files)

**Comment by gbrdbs** [comment]
letrehozaskor keszit egy map-et és egy listet is

getMap(): a map szerkezete a json formatummal egyezik
getList(): a lista csak string listakent tartalmazza a beolvasott csv sorokat
