### ISSUE TITLE
Creating JsonParser

### ISSUE THREAD

**Issue by spiralfuzet** [spiralfuzet/AirportSimulation#12]
http://json.org/
https://hu.wikipedia.org/wiki/JSON

**Comment by gbrdbs** [comment]
minta json kéne összerakni az airport és az airplane kész specikációja esetén

**Comment by gbrdbs** [comment]
csináljak?

**Comment by sugeeism** [comment]
ahham, ma megcsinalom hozza a parsert

**Comment by gbrdbs** [comment]
task 13 és 14-hez tartozó branchen fenn van a minta (13-14_Defining-Json-files)

**Comment by sugeeism** [comment]
hozzaadtam a javaee jsonparser lib-et a projekthez :)
(branch: 12_Creating_JsonParser)

**Comment by gbrdbs** [comment]
remeltem keszul kod is:)

**Comment by sugeeism** [comment]
mar van, csak meg szuttyogok a tesztekkel :)

**Comment by gbrdbs** [comment]
valami parsert nem kellett volna csinalni?
ok hogy ez mindent megcsinal, de igy hogy lesz egyenerteku a csv parserral

**Comment by gbrdbs** [comment]
feltoltam a 11-es branchre

**Comment by sugeeism** [comment]
ugy gondoltam, hogy reader osztalyok hasznaljak a parsereket.
a reader osztalyok feluletein keresztul pedig a builderek elerik az adatokat
