### ISSUE TITLE
Creating Airplane

### ISSUE THREAD

**Issue by spiralfuzet** [spiralfuzet/AirportSimulation#4]
- utasok / max utas
- üzemanyag / fogyasztás (logika ami csökkenti)
- összes megtett út
- karbantartás
- akt magasság
- állapot (úton van?, földön van, éppen elindul, éppen leszáll)

**Comment by gbrdbs** [comment]
valahol a default airportot is meg kell adni az airplainekre, amiből indul a szimuláció.
ezt itt kellene tárolni

**Comment by gbrdbs** [comment]
ID / név is kellene

**Comment by gbrdbs** [comment]
mégse tároljuk itt a default airportot

**Comment by doby86** [comment]
see task 13 and 15

**Comment by gbrdbs** [comment]
mivel nem történt eddig semmi, nyitottam egy branchet:
4_Creating_Airplane
azon átdolgozom magam is. max nem merge ezt.

**Comment by sugeeism** [comment]
este hozzaigazotom a builder-t es javitom a json file-t.

**Comment by gbrdbs** [comment]
egy dolgot vettem hozza: String id field került be
elvileg hozzáigazítottam mindent, nézz rá kérlek ezen a branchen a json részre hogy jó lett-e

**Comment by gbrdbs** [comment]
ha igen, szerintem most több nem kell az airplane-be

**Comment by sugeeism** [comment]
jo lett.
hozzaadtam a .json filehoz az id objectet.
4_Creating_Airplane

**Comment by gbrdbs** [comment]
mergeltem az egeszet. közben készült egy új airplane qwerzasd által, azzal is durva merge lett, hogy legalabb a tesztek fussanak ma este. elnézést qwertzasd, hogy az Airplane bean-ed nem lett így annyira bean, csak közben máshol haladtunk vele.
