### ISSUE TITLE
Creating Airport

### ISSUE THREAD

**Issue by spiralfuzet** [spiralfuzet/AirportSimulation#5]
- befogadóképesség
- repülők (állapot szerint)
- többi repülőtér (gráf)

**Comment by gbrdbs** [comment]
Szükséges még:
ID / név

**Comment by gbrdbs** [comment]
see task 14 and 16

**Comment by gbrdbs** [comment]
ez hogy all?

**Comment by sugeeism** [comment]
Ezt most a 8_Creating_Airport branchbol kellene tovabbvinni?

**Comment by gbrdbs** [comment]
8_Creating_AirportBuilder
Jah, teljesen mindegy, honnan.
De most hogy felrúgtam a fejl. sorrendet, onnan kéne

**Comment by gbrdbs** [comment]
ha valami elganyolodik a csv-s szarsagaimban, akkor majd kijavitom.
de már csak holnap
over and out

**Comment by sugeeism** [comment]
oksa
bye

**Comment by sugeeism** [comment]
letrehoztam az airportot
5_Creating_Airport
