### ISSUE TITLE
Creating AirPlaneBuilder

### ISSUE THREAD

**Issue by spiralfuzet** [spiralfuzet/AirportSimulation#7]
- fájlból

**Comment by spiralfuzet** [comment]
Egyáltalán nem beszéltük meg a fájlformátumot.

**Comment by gbrdbs** [comment]
Json

**Comment by spiralfuzet** [comment]
az nem túl adatbázisos, de ha cserélhető beolvasó interfészt akarunk csinálni, akkor legyen json

**Comment by sugeeism** [comment]
megcsinalom, cserelheto interfesszel

**Comment by spiralfuzet** [comment]
Felvszek két új ticketet általános JSON és CSV felolvasokra

**Comment by sugeeism** [comment]
felkerult az AirplaneReader es a Builder osztalya. A parser miatt kicsit modositottam a .json fajlon.
7_Creating_AirplaneBuilder

**Comment by gbrdbs** [comment]
hát ezzel most eltűntetted a repülők id-ját

**Comment by gbrdbs** [comment]
csinalok hozza csv buildert

**Comment by sugeeism** [comment]
huh, tenyleg.
nem tudtam mashogy parseolni a jsonobjectre.
atkerulhet az ID a blokkon belulre?

**Comment by gbrdbs** [comment]
nekem mindegy, csak nem ertem igy tavolrol, hogy miert kellett azonos nevu objectname mindenhova.

**Comment by sugeeism** [comment]
a jsonparsernek meg kell adni az object nevet, amit fel olvas (eddig nem talaltam lattam olyan megodust, ami enelkul is menne). igy most array-ben vannak tarolva es a megadott objectname alapjan olvassa fel.

**Comment by sugeeism** [comment]
de elcsesztem az atalakitast ezekszerint :)

**Comment by gbrdbs** [comment]
csv-s builder mellerakva erre a branchre, illetve belemergeltem a csv parsert.
utobbi nem a legjobb, nem illik bele abba amit irtal egyelore

**Comment by sugeeism** [comment]
Kozos interfacenek az Airplane jo lenne?( a reader osztalyoknal )
vagy inkabb valami string lista?

**Comment by sugeeism** [comment]
Javittottam a reader interfacet, igymar solid
7_Creating_AirplaneBuilder
