### ISSUE TITLE
Creating AirPortBuilder

### ISSUE THREAD

**Issue by spiralfuzet** [spiralfuzet/AirportSimulation#8]
- fájlból
- kapcsolatok
- etc

**Comment by spiralfuzet** [comment]
Egyáltalán nem beszéltük meg a fájlformátumot.

**Comment by gbrdbs** [comment]
gyorsan lemasolom erre is a csv buildert

**Comment by gbrdbs** [comment]
CsvAirportBuilder és teszt megvan
KELL!!!!
Airport class
AirportBuilder interface

**Comment by gbrdbs** [comment]
AirportBuilder interface hozzaadva

már csak az Airport class kell
